version: "3.7"
 
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql_container
    #restart: always
    environment:
        MYSQL_ROOT_HOST: '%'
        MYSQL_USER: 'docker'
        MYSQL_PASSWORD: 'docker'
        MYSQL_DATABASE: 'docker'
        MYSQL_ROOT_PASSWORD: 'adm123'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - mysqldb:/var/lib/mysql

  api:
    container_name: api_container
    #restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: production #firing base, not production
    volumes:
      - ./src:/app/src
      # - ./nodemon.json:/app/nodemon.json
    expose:
      - 8886
    ports:
      - "8887:8886"
    command: yarn start

  redis:
    container_name: redis_container
    image: redis:6.2-alpine
    #restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - rediscache:/data

  
# Names our volume
volumes:
  mysqldb:
  rediscache:
    driver: local
